- name: Build and SonarCloud Scan
  run: |
    mvn -B verify sonar:sonar \
    -Dsonar.projectKey=SAST-NEW \
    -Dsonar.organization=security-poc-max \
    -Dsonar.host.url=https://sonarcloud.io
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
