name: SonarCloud Scan

on:
  push:
    branches:
      - master

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN1 }}
        with:
          args: >
            -Dsonar.projectKey=SAST-NEW
            -Dsonar.organization=security-poc-max
